# Generated by Django 3.0 on 2019-12-17 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='tb_projects',
        ),
    ]
